<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pinba.proto

namespace Pinba;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Pinba.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string hostname = 1;</code>
     */
    protected $hostname = '';
    /**
     * Generated from protobuf field <code>string server_name = 2;</code>
     */
    protected $server_name = '';
    /**
     * Generated from protobuf field <code>string script_name = 3;</code>
     */
    protected $script_name = '';
    /**
     * Generated from protobuf field <code>uint32 request_count = 4;</code>
     */
    protected $request_count = 0;
    /**
     * Generated from protobuf field <code>uint32 document_size = 5;</code>
     */
    protected $document_size = 0;
    /**
     * Generated from protobuf field <code>uint32 memory_peak = 6;</code>
     */
    protected $memory_peak = 0;
    /**
     * Generated from protobuf field <code>float request_time = 7;</code>
     */
    protected $request_time = 0.0;
    /**
     * Generated from protobuf field <code>float ru_utime = 8;</code>
     */
    protected $ru_utime = 0.0;
    /**
     * Generated from protobuf field <code>float ru_stime = 9;</code>
     */
    protected $ru_stime = 0.0;
    /**
     * Generated from protobuf field <code>repeated uint32 timer_hit_count = 10;</code>
     */
    private $timer_hit_count;
    /**
     * Generated from protobuf field <code>repeated float timer_value = 11;</code>
     */
    private $timer_value;
    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_count = 12;</code>
     */
    private $timer_tag_count;
    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_name = 13;</code>
     */
    private $timer_tag_name;
    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_value = 14;</code>
     */
    private $timer_tag_value;
    /**
     * Generated from protobuf field <code>repeated string dictionary = 15;</code>
     */
    private $dictionary;
    /**
     * Generated from protobuf field <code>uint32 status = 16;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>uint32 memory_footprint = 17;</code>
     */
    protected $memory_footprint = 0;
    /**
     * Generated from protobuf field <code>repeated .Pinba.Request requests = 18;</code>
     */
    private $requests;
    /**
     * Generated from protobuf field <code>string schema = 19;</code>
     */
    protected $schema = '';
    /**
     * Generated from protobuf field <code>repeated uint32 tag_name = 20;</code>
     */
    private $tag_name;
    /**
     * Generated from protobuf field <code>repeated uint32 tag_value = 21;</code>
     */
    private $tag_value;
    /**
     * Generated from protobuf field <code>repeated float timer_ru_utime = 22;</code>
     */
    private $timer_ru_utime;
    /**
     * Generated from protobuf field <code>repeated float timer_ru_stime = 23;</code>
     */
    private $timer_ru_stime;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hostname
     *     @type string $server_name
     *     @type string $script_name
     *     @type int $request_count
     *     @type int $document_size
     *     @type int $memory_peak
     *     @type float $request_time
     *     @type float $ru_utime
     *     @type float $ru_stime
     *     @type int[] $timer_hit_count
     *     @type float[] $timer_value
     *     @type int[] $timer_tag_count
     *     @type int[] $timer_tag_name
     *     @type int[] $timer_tag_value
     *     @type string[] $dictionary
     *     @type int $status
     *     @type int $memory_footprint
     *     @type \Pinba\Request[] $requests
     *     @type string $schema
     *     @type int[] $tag_name
     *     @type int[] $tag_value
     *     @type float[] $timer_ru_utime
     *     @type float[] $timer_ru_stime
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pinba::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string hostname = 1;</code>
     * @return string
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     * Generated from protobuf field <code>string hostname = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHostname(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->hostname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string server_name = 2;</code>
     * @return string
     */
    public function getServerName()
    {
        return $this->server_name;
    }

    /**
     * Generated from protobuf field <code>string server_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setServerName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->server_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string script_name = 3;</code>
     * @return string
     */
    public function getScriptName()
    {
        return $this->script_name;
    }

    /**
     * Generated from protobuf field <code>string script_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setScriptName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->script_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 request_count = 4;</code>
     * @return int
     */
    public function getRequestCount()
    {
        return $this->request_count;
    }

    /**
     * Generated from protobuf field <code>uint32 request_count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRequestCount(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->request_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 document_size = 5;</code>
     * @return int
     */
    public function getDocumentSize()
    {
        return $this->document_size;
    }

    /**
     * Generated from protobuf field <code>uint32 document_size = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDocumentSize(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->document_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 memory_peak = 6;</code>
     * @return int
     */
    public function getMemoryPeak()
    {
        return $this->memory_peak;
    }

    /**
     * Generated from protobuf field <code>uint32 memory_peak = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMemoryPeak(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->memory_peak = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float request_time = 7;</code>
     * @return float
     */
    public function getRequestTime()
    {
        return $this->request_time;
    }

    /**
     * Generated from protobuf field <code>float request_time = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setRequestTime(float $var)
    {
        $this->request_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float ru_utime = 8;</code>
     * @return float
     */
    public function getRuUtime()
    {
        return $this->ru_utime;
    }

    /**
     * Generated from protobuf field <code>float ru_utime = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setRuUtime(float $var)
    {
        $this->ru_utime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float ru_stime = 9;</code>
     * @return float
     */
    public function getRuStime()
    {
        return $this->ru_stime;
    }

    /**
     * Generated from protobuf field <code>float ru_stime = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setRuStime(float $var)
    {
        $this->ru_stime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_hit_count = 10;</code>
     * @return RepeatedField<int>
     */
    public function getTimerHitCount()
    {
        return $this->timer_hit_count;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_hit_count = 10;</code>
     * @param int[] $var
     * @return $this
     */
    public function setTimerHitCount(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->timer_hit_count = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float timer_value = 11;</code>
     * @return RepeatedField<float>
     */
    public function getTimerValue()
    {
        return $this->timer_value;
    }

    /**
     * Generated from protobuf field <code>repeated float timer_value = 11;</code>
     * @param float[] $var
     * @return $this
     */
    public function setTimerValue(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->timer_value = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_count = 12;</code>
     * @return RepeatedField<int>
     */
    public function getTimerTagCount()
    {
        return $this->timer_tag_count;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_count = 12;</code>
     * @param int[] $var
     * @return $this
     */
    public function setTimerTagCount(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->timer_tag_count = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_name = 13;</code>
     * @return RepeatedField<int>
     */
    public function getTimerTagName()
    {
        return $this->timer_tag_name;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_name = 13;</code>
     * @param int[] $var
     * @return $this
     */
    public function setTimerTagName(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->timer_tag_name = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_value = 14;</code>
     * @return RepeatedField<int>
     */
    public function getTimerTagValue()
    {
        return $this->timer_tag_value;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 timer_tag_value = 14;</code>
     * @param int[] $var
     * @return $this
     */
    public function setTimerTagValue(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->timer_tag_value = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string dictionary = 15;</code>
     * @return RepeatedField<string>
     */
    public function getDictionary()
    {
        return $this->dictionary;
    }

    /**
     * Generated from protobuf field <code>repeated string dictionary = 15;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDictionary(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->dictionary = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 16;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 memory_footprint = 17;</code>
     * @return int
     */
    public function getMemoryFootprint()
    {
        return $this->memory_footprint;
    }

    /**
     * Generated from protobuf field <code>uint32 memory_footprint = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setMemoryFootprint(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->memory_footprint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Pinba.Request requests = 18;</code>
     * @return RepeatedField<\Pinba\Request>
     */
    public function getRequests()
    {
        return $this->requests;
    }

    /**
     * Generated from protobuf field <code>repeated .Pinba.Request requests = 18;</code>
     * @param \Pinba\Request[] $var
     * @return $this
     */
    public function setRequests(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pinba\Request::class);
        $this->requests = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string schema = 19;</code>
     * @return string
     */
    public function getSchema()
    {
        return $this->schema;
    }

    /**
     * Generated from protobuf field <code>string schema = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setSchema(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->schema = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 tag_name = 20;</code>
     * @return RepeatedField<int>
     */
    public function getTagName()
    {
        return $this->tag_name;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 tag_name = 20;</code>
     * @param int[] $var
     * @return $this
     */
    public function setTagName(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->tag_name = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 tag_value = 21;</code>
     * @return RepeatedField<int>
     */
    public function getTagValue()
    {
        return $this->tag_value;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 tag_value = 21;</code>
     * @param int[] $var
     * @return $this
     */
    public function setTagValue(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->tag_value = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float timer_ru_utime = 22;</code>
     * @return RepeatedField<float>
     */
    public function getTimerRuUtime()
    {
        return $this->timer_ru_utime;
    }

    /**
     * Generated from protobuf field <code>repeated float timer_ru_utime = 22;</code>
     * @param float[] $var
     * @return $this
     */
    public function setTimerRuUtime(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->timer_ru_utime = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float timer_ru_stime = 23;</code>
     * @return RepeatedField<float>
     */
    public function getTimerRuStime()
    {
        return $this->timer_ru_stime;
    }

    /**
     * Generated from protobuf field <code>repeated float timer_ru_stime = 23;</code>
     * @param float[] $var
     * @return $this
     */
    public function setTimerRuStime(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->timer_ru_stime = $arr;

        return $this;
    }

}

